	SUBROUTINEFILLERUP(BIG,NOISE,IXIN,IYIN,JFAST,JSLOW)
	PARAMETER (MAXFIL = 1024)
	INCLUDE 'TUNEABLE'
	COMMON /SEARCH/ NSTOT, THRESH
	COMMON /SUBRASTER/  Z(MAXFIL), XX(MAXFIL), YE(MAXFIL)
	COMMON /CRUDESTAT/ NPT, SUM0, SUM1, SUM2, MAXVAL, XM, YM
	COMMON /UNITIZE/ UFACTOR
	INTEGER*2 BIG(JFAST, JSLOW)
	INTEGER*4 NOISE(JFAST,JSLOW)
	INTEGER*2 IX(2)
        INTEGER*4 IXTEMP1, IXTEMP2
	EQUIVALENCE (IX,R4)
	DATA MAGIC / 2147483647/
	UFACTOR2 = UFACTOR**2
	SNLIM2 = SNLIM**2
	MAXVAL = BIG( min(max(IXIN,1),JFAST), min(max(IYIN,1),JSLOW) )         
	XM = 0
	YM = 0
	NPT = 0
	SUM0 = 0
	SUM1 = 0
	SUM2 = 0
	IXDUM = IXIN
	IYDUM = IYIN
C	BESTSKY = GUESS1(A,DUMMY,IXDUM,IYDUM)	
	JLO = MAX0(IYIN - IRECT(2)/2, 1)
	JHI = MIN0(IYIN + IRECT(2)/2, JSLOW)
	DO 2757 J = JLO, JHI
	  ILO = MAX0(IXIN - IRECT(1)/2, 1)
	  IHI = MIN0(IXIN + IRECT(1)/2, JFAST)
	  DO 2758 I = ILO, IHI
	    IBIG = BIG(I, J)
	    INOISE = NOISE(I, J)
	    IF (IBIG*IBIG .LT. SNLIM2*INOISE) THEN
	    ELSE IF (INOISE .GE. MAGIC) THEN
C	    ELSE IF (IBIG .LT. BESTSKY/2) THEN		
	    ELSE
	      IX(1) = I - IXIN
	      IX(2) = J - IYIN
	      IF (IBIG .GT. MAXVAL) THEN
                IXTEMP1 = ABS(IX(1))
                IXTEMP2 = ABS(IX(2)) 
c                IF (MAX0(ABS(IX(1)), ABS(IX(2))) .LE. 1) THEN
                IF (MAX0(IXTEMP1, IXTEMP2) .le. 1) THEN
             	  MAXVAL = IBIG
		  XM = IX(1)
		  YM = IX(2)
		END IF
	      END IF
C	      SUM1 = SUM1 + IBIG			!FOSSILS
C	      SUMX = SUMX + IBIG*IX(1)			!FOSSILS
C	      SUMY = SUMY + IBIG*IX(2)			!FOSSILS
	      NPT = NPT + 1
	      XX(NPT) = R4
	      Z(NPT) = FLOAT(IBIG)/UFACTOR
	      YE(NPT) = NOISE(I,J)/UFACTOR2
	      TEMP = 1/YE(NPT)
	      SUM0 = SUM0 + TEMP
	      SUM1 = SUM1 + FLOAT(IBIG)*TEMP
	    END IF
2758	  CONTINUE
2757	CONTINUE
	IF (SUM0 .NE. 0) THEN
	  SUM2 = SUM1/SUM0			
	END IF
	RETURN
	END





