	SUBROUTINE MAKEMASK(ONESTAR)
	PARAMETER (MMAX = 7)
	INCLUDE 'TUNEABLE'
	COMMON /PASSMASK/ STARMASK(-8:8, -8:8)	
	INTEGER*2 IX(2)
	DIMENSION A(MMAX), FA(MMAX)
	EXTERNAL ONESTAR
        DUMX = 0.
        DUMY = 0.
	CALL PARINTERP( DUMX, DUMY, A)
c
c  Rearranged parameter values.
c
	A(1) = 0			
	A(2) = 1			
	A(3) = 0			
	A(4) = 0			
	DO 2757 J = -IYBY2, IYBY2
	  IX(2) = J
	  DO 2758 I = -IXBY2, IXBY2
	    IX(1) = I
	    STARMASK(I,J) = ONESTAR(IX, A, FA, M, MMAX)
2758	  CONTINUE
2757	CONTINUE
	RETURN
	END
