	SUBROUTINE MAKENOISE(BIG, NOISE, NFAST, NSLOW)
	INCLUDE 'TUNEABLE'
	COMMON /SEARCH/ NSTOT, THRESH
	INTEGER*2 BIG(NFAST,NSLOW)
	INTEGER*4 NOISE(NFAST,NSLOW)
	LOGICAL BADLINE, BADPIX
	DATA MAGIC / 2147483647/
	JTOP = MIN0(ITOP, 32767)
	JBOT = MAX0(IBOT, -32768)
	TEMP1 = (RNOISE/EPERDN)**2		
	TEMP2 = 1/EPERDN			
	DO 2757 I = 1, NSLOW
          BADLINE = (I .LE. NBADBOT .OR. I .GT. NSLOW - NBADTOP)
          DO 2758 J = 1, NFAST
	    IF (BADLINE) THEN
	      NOISE(J,I) = MAGIC
	    ELSE
	      BADPIX = (J .LE. NBADLEFT .OR. J .GT. NFAST - NBADRIGHT)
	      IF (BADPIX) THEN
		NOISE(J,I) = MAGIC
	      ELSE IF	(BIG(J,I) .GE. JTOP)THEN
		NOISE(J,I) = MAGIC
	      ELSE IF	(BIG(J,I) .LE. JBOT)THEN
		NOISE(J,I) = MAGIC
	      ELSE
                if (big(j,i) .gt. 0) then
		NOISE(J,I) = BIG(J,I)*TEMP2 + TEMP1
                else
                noise(j,i) = temp1
                end if
	      END IF
	    END IF
2758	  CONTINUE
2757	CONTINUE
	RETURN
	END
