	SUBROUTINE PARUPD (A, STARPAR, IX, IY)
C:  THIS SUBROUTINE IS PROFILE SPECIFIC AND NEEDS REWRITING FOR EACH
C:  FITTING FUNCTION.
        include 'TUNEABLE'
	COMMON /CRUDESTAT/ NPT, SUM1, SUMX, SUMY, MAXVAL, XM, YM
	COMMON /UNITIZE / UFACTOR
	DIMENSION A(NPMAX), STARPAR(NPMAX)
	DO 2757 K = 1, NPAR
	  STARPAR(K) = A(K)
2757	CONTINUE
c
c Changed indices.
c
	STARPAR(1) = A(1)*UFACTOR
	STARPAR(2) = A(2)*UFACTOR
	STARPAR(3) = STARPAR(3) + IX
	STARPAR(4) = STARPAR(4) + IY
	RETURN
	ENTRY TWOUPD (A, STARPAR, IX, IY)
	STARPAR(1) = A(1)			
	DO 2758 I = 0, 3, 3
c
c  Changed indices.
c
	  STARPAR(2 + I) = A(2 + I)		
	  STARPAR(3 + I) = A(3 + I) + IX
	  STARPAR(4 + I) = A(4 + I) + IY
2758	CONTINUE
	RETURN
	END
