c
c  This is the skyfun for the plane law.
c
	FUNCTION SKYFUN(IX, A, FA, M, MMAX)
	COMMON /DRFAKE/ NEEDIT
	COMMON /UNDERGND/ NFAST, NSLOW
	LOGICAL NEEDIT
	DIMENSION A(1),FA(1)
	INTEGER*2 IX(2)
	DATA HALF / 0.5 /
C	X = HALF*(IX(1) - HALF*NFAST)/(HALF*NFAST)
C	Y = HALF*(IX(2) - HALF*NSLOW)/(HALF*NSLOW)
	FA(1) = 1
	FA(2) = HALF*(IX(1) - HALF*NFAST)/(HALF*NFAST)
	FA(3) = HALF*(IX(2) - HALF*NSLOW)/(HALF*NSLOW)
	TEMP = 0
	DO 2757 I = 1, 3
	  TEMP = TEMP + A(I)*FA(I)
2757	CONTINUE
	SKYFUN = TEMP	
	RETURN
	END
