	FUNCTION TOOFAINT(STARPAR, ERR)
	INCLUDE 'TUNEABLE'
	COMMON /SEARCH/ NSTOT,THRESH
	COMMON /UNITIZE/ UFACTOR
	DIMENSION STARPAR(NPMAX)
	DIMENSION ERR(NPMAX)
	LOGICAL TOOFAINT
c
c  Changed indices.
c
        CMIN = 1.0 
	TOOFAINT = STARPAR(2) .LT. CMIN
	IF (ERR(2) .GT. 0) THEN
	    SIG2 = (STARPAR(2)/UFACTOR) ** 2 / ERR(2)
c
	    TOOFAINT = TOOFAINT .OR. SIG2 .LT. CRIT7
	if(lverb.gt.30) then
	   write(6,*) 'SIG2 = ', SIG2 
	end if
	END IF
	RETURN
	END
	
